"use client";

import { ThemeProvider } from "@/components";
import { ToastContainer } from "react-toastify";
import "./globals.scss";
import styles from './layout.module.scss';

// export const metadata = {
//   title: "Create Next Asdfsdfsdfpp",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={styles.body}>
          {children}
          <ToastContainer autoClose={2000} />
        </body>
      </html>
    </ThemeProvider>
  );
}
